### ISSUE TITLE
Geo-location Filtering

### ISSUE THREAD

**Issue by nfspeedypur** [Chicago/opengrid-svc-template#3]
Currently Geo-location location filtering only happens on the UI side.  However there are APIs, like Plenar.io that offer Geo-location filtering, when using the API.  So it would be nice to have some way of saying if the service can handle the filtering and then pass the Geo-location data down to the service, in a API call.

**Comment by tomschenkjr** [comment]
## Proposed API changes:
    
### new `/capabilities` resource

Sample response:

```
{
    “geoSpatialFiltering” : “true”
}
``` 

### new "geo" param to ` /{dataset id}/query` resource
 
geo param=> geometry object
 
```json
{
  "type": "Polygon",
  "coordinates": [
    [
        [
          -87.68353700637817,
          41.79390441395615
        ],
        [
          -87.68353700637817,
          41.79883151649387
        ],
        [
          -87.67439603805542,
          41.79883151649387
        ],
        [
          -87.67439603805542,
          41.79390441395615
        ],
        [
          -87.68353700637817,
          41.79390441395615
        ]
      ]
    ]
}
```
 
### data tier

1. MongoDB -> `$geoWithin` (geometry can be polygon or multiPolygon)

2. Plenar.IO -> `location_geom_within`

Does Plenar.IO support `"type": "MultiPolygon"`?

**Comment by WillEngler** [comment]
No, we don't yet support multipolygons in API calls. How would you describe the priority of multipolygon support? Is it a must-have or a nice-to-have?

**Comment by WillEngler** [comment]
It turns out we support MultiPolygons and I just wasn't aware. Pleasant surprise! I made our multipolygon support "official" by adding it to our API test suite.

Here's a working example with a multipolygon consisting of a rectangle over downtown and a rectangle over Hyde Park:

http://plenar.io/v1/api/detail/?dataset_name=flu_shot_clinic_locations_2013_standard_format&obs_date__ge=2013-01-01&obs_date__le=2013-12-31&location_geom__within={%22type%22:%22MultiPolygon%22,%22coordinates%22:[[[[-87.616782188416,41.780144914492],[-87.616782188416,41.802286661135],[-87.569317817688,41.802286661135],[-87.569317817688,41.780144914492],[-87.616782188416,41.780144914492]]],[[[-87.667894363403,41.851662061565],[-87.667894363403,41.891799452396],[-87.597513198853,41.891799452396],[-87.597513198853,41.851662061565],[-87.667894363403,41.851662061565]]]]}

**Comment by tomschenkjr** [comment]
@WillEngler - that's about the best surprise a developer can ever find.

@nfspeedypur and @rladines - does this work and fit into the semantics?

**Comment by rladines** [comment]
As far as the API enhancement is concerned, this should work since this looks to be just the standard geoJson MultiPolygon construct.

**Comment by WillEngler** [comment]
@rladines To confirm, yes, it is just standards-compliant GeoJSON.

**Comment by PriyaDoIT** [comment]
Will not commit to GitHub until opengrid#190 is complete
